name: Angular GitHub CI
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - run: npm ci
      - run: npm run build -- --base-href '/solidcryptpad/'
      - run: cp ./dist/solid-crypt-pad/index.html ./dist/solid-crypt-pad/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main'}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/solid-crypt-pad
